# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.
# [app]
# port=8080
# ^^ do we need these 2 lines?  the scaffolding might define it already
[gs-accessing-data-mysql]
port=8080

[spring.jpa.hibernate]
ddl-auto="none"

[spring.datasource]
url="jdbc:mysql://127.0.0.1:3306/db_example"
username="springuser"
password="ThePassword"
database_schema="db_example"
