# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.
port=8080

[spring.jpa.hibernate]
ddl-auto="create"

[spring.datasource]
url="jdbc:mysql://localhost:3306/db_example"
username="springuser"
password="ThePassword"


